### ISSUE TITLE
 FixedLocator locations matplotlib error on running obj_det_plot_metrics...

### ISSUE THREAD

**Issue by syedtihaamahmad** [IntelLabs/PyTorchALFI#3]
ValueError: The number of FixedLocator locations (0), usually from a call to set_ticks, does not match the number of ticklabels (1).

**Comment by SyedShaQutub** [comment]
@syedtihaamahmad  Could you please be more precise, a error trace could help us fix if at this is a common issue. 
What features have you selected to plot the results? Are you trying to plot the results of 1 model but a different set of experiments or multiple models?

**Comment by syedtihaamahmad** [comment]
It occurred while trying to fix this error.

File path != valid
Traceback (most recent call last):
  File "/home/tawm9/pytorchalfi/evaluation/obj_det_plot_metrics_all_models.py", line 20, in <module>
    obj_det_analysis(sys.argv)
  File "/home/tawm9/pytorchalfi/evaluation/obj_det_plot_metrics_all_models.py", line 17, in obj_det_analysis
    obj_det_plot_metrics(exp_folder_paths=exp_folder_paths)
  File "/home/tawm9/pytorchalfi/alficore/evaluation/sdc_plots/obj_det_plot_metrics_all_models.py", line 1070, in obj_det_plot_metrics
    plot_metric(mns_orig, errs_orig, mns_corr, errs_corr, leg, yname, sv_name, ax_leg)
  File "/home/tawm9/pytorchalfi/alficore/evaluation/sdc_plots/obj_det_plot_metrics_all_models.py", line 234, in plot_metric
    ax.set_ylim([0, max(max(mns_orig), max(mns_corr))*1.1+0.1])
ValueError: max() arg is an empty sequence
